version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: f1_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - f1_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: f1_redis
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - f1_network

volumes:
  postgres_data:
  redis_data:

networks:
  f1_network:
    driver: bridge