# Remove the version line as it's obsolete
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: f1_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Allow connections from host
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - f1_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      bash -c "
      echo 'host all all 0.0.0.0/0 md5' >> /var/lib/postgresql/data/pg_hba.conf &&
      echo 'host all all ::/0 md5' >> /var/lib/postgresql/data/pg_hba.conf &&
      echo \"listen_addresses = '*'\" >> /var/lib/postgresql/data/postgresql.conf &&
      docker-entrypoint.sh postgres
      "

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: f1_redis
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - f1_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  f1_network:
    driver: bridge